config:
  global_param1: abc
  global_param2: cbd
  models:
      aws:
        module_name: ext_llm.aws_llm
        class_name: AwsLlm
        aws_access_key_id: "123"
        aws_secret_access_key: "456"
      groq:
        module_name: ext_llm.groq_llm
        class_name: GroqLlm
        param1: "13"
        param2: "http://example.com"